### PR TITLE
fix(interceptors): prevent overriding existing headers

### LINKED ISSUE #27: [bug]: custom content-type header is overridden
### A clear and concise description of what the feature is

https://docs.strapi.io/dev-docs/plugins/upload

### Why should this feature be included?

https://docs.strapi.io/dev-docs/plugins/upload

### Please provide an example for how this would work

_No response_

Edit: so i found bug:

if i use `.fetch('/upload'..., {
  headers: new Headers({
    'Content-Type': 'multipart/form-data',
  }),
}`

my header overrides 😢

CleanShot 2025-01-13 at 03 42 32@2x

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Make sure the `setDefaultHeaders` HTTP interceptor doesn't override manually set headers.

### Why is it needed?

see https://github.com/strapi/sdk-js/issues/27

### How to test it?

Using `sdk.fetch` with a custom content type header should not override said header with `application/json`

Alternatively, running the unit tests ensures the behavior is correct based on `tests/unit/sdk.test.ts` and `tests/unit/sdk.test.ts`

### Related issue(s)/PR(s)

fix #27

### CODE REVIEW

File: src/interceptors/http.ts [hunk 1]
```diff
@@ -26,8 +26,16 @@ export class HttpInterceptors {
    *```
    */
   public static setDefaultHeaders(): RequestInterceptor {
+    const DEFAULT_HEADERS = new Map([['Content-Type', 'application/json']]);
+
     return ({ request }) => {
-      request.headers.set('Content-Type', 'application/json');
+      for (const [key, value] of DEFAULT_HEADERS.entries()) {
```
Comment (innerdvations) [inline src/interceptors/http.ts:32]: we might want to compare it case-insensitive or else if someone adds `'content-type' -> 'text/plain'` it will still be included

Comment (Convly) [reply src/interceptors/http.ts:32]: The `Headers.prototype.has` and `Headers.prototype.get` already handle case-insensitive matching. I've added a test to make sure the behavior stays consistent across node versions

Comment (Convly) [reply src/interceptors/http.ts:32]: (Headers names are meant to be case-insensitive)

Comment (innerdvations) [reply src/interceptors/http.ts:32]: ahhh, oops, sorry!

**Review by innerdvations — APPROVED** [review]
LGTM!

File: tests/unit/interceptors/http.test.ts [hunk 2]
```diff
@@ -28,7 +28,22 @@ describe('HTTP Interceptors', () => {
...
+        headers: { 'content-type': 'text/plain' },
+      });
+
+      const interceptor = HttpInterceptors.setDefaultHeaders();
+
+      // Act
+      await interceptor({ request });
+
+      // Assert
+      expect(request.headers.get('Content-Type')).toBe('text/plain');
```
Comment (jhoward1994) [inline tests/unit/interceptors/http.test.ts:46]: I'm a bit confused by this. Reading `src/interceptors/http.ts` I'd expect this to be set to `application/json` from the default headers as (lowercase) `content-type` is not in the map `DEFAULT_HEADERS`?

Comment (Convly) [reply tests/unit/interceptors/http.test.ts:46]: Two things basically:
- Headers’ names are checked case insensitive. This is achieved through the HTTP Headers instance's methods (.get/.has) that already handle this for us. 
- Headers should default to `application/json` only if the user has not manually overridden the value (which is the case here), hence the return value

Comment (jhoward1994) [reply tests/unit/interceptors/http.test.ts:46]: Makes sense thanks!

**Review by jhoward1994 — APPROVED** [review]

**Comment by innerdvations** [comment]
Tested, works for me!
